# ----------- Build Stage -----------
FROM golang:1.25-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o api-server ./cmd/api

# ----------- Final Stage -----------
FROM alpine:3.21
RUN apk add --no-cache ca-certificates wget
EXPOSE 8080
COPY --from=builder /app/api-server /api-server
ENTRYPOINT ["/api-server"]
