// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.3 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	ApiKeyAuthScopes = "ApiKeyAuth.Scopes"
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Defines values for TraceStatus.
const (
	TraceStatusError   TraceStatus = "error"
	TraceStatusOk      TraceStatus = "ok"
	TraceStatusUnknown TraceStatus = "unknown"
)

// Error Standard error response format for all API errors.
type Error struct {
	// Code HTTP status code
	Code int32 `json:"code"`

	// Details Additional error details (optional)
	Details *map[string]interface{} `json:"details,omitempty"`

	// Message Human-readable error message
	Message string `json:"message"`
}

// Event Represents a UI session event for session replay functionality.
// Events capture user interactions and application state changes.
type Event struct {
	// EventId Unique identifier for this event
	EventId openapi_types.UUID `json:"event_id"`

	// EventType Type of event (optional, for categorization)
	EventType *string `json:"event_type,omitempty"`

	// Payload Event-specific data (flexible schema)
	Payload map[string]interface{} `json:"payload"`

	// SessionId ID of the session this event belongs to
	SessionId openapi_types.UUID `json:"session_id"`

	// Tags Key-value metadata for the event
	Tags *map[string]string `json:"tags,omitempty"`

	// Timestamp When the event occurred (RFC3339 format)
	Timestamp time.Time `json:"timestamp"`
}

// Span Represents a single operation within a trace.
// Spans are the building blocks of distributed traces.
type Span struct {
	// DurationMs Duration of the span in milliseconds
	DurationMs int64 `json:"duration_ms"`

	// OperationName Name of the operation (optional)
	OperationName *string `json:"operation_name,omitempty"`

	// ParentId ID of the parent span (null for root spans)
	ParentId *openapi_types.UUID `json:"parent_id,omitempty"`

	// ServiceName Name of the service that created this span
	ServiceName string `json:"service_name"`

	// SpanId Unique identifier for this span
	SpanId openapi_types.UUID `json:"span_id"`

	// StartTime When the span started (RFC3339 format)
	StartTime time.Time `json:"start_time"`

	// Tags Key-value metadata for the span
	Tags *map[string]string `json:"tags,omitempty"`

	// TraceId ID of the parent trace
	TraceId openapi_types.UUID `json:"trace_id"`
}

// Trace Represents a distributed trace containing metadata about a single request flow.
type Trace struct {
	// DurationMs Total duration of the trace in milliseconds
	DurationMs int64 `json:"duration_ms"`

	// RootSpanId ID of the root span (optional, may be null)
	RootSpanId *openapi_types.UUID `json:"root_span_id,omitempty"`

	// ServiceName Name of the service that initiated the trace
	ServiceName string `json:"service_name"`

	// StartTime When the trace started (RFC3339 format)
	StartTime time.Time `json:"start_time"`

	// Status Final status of the trace
	Status TraceStatus `json:"status"`

	// Tags Key-value metadata associated with the trace
	Tags *map[string]string `json:"tags,omitempty"`

	// TraceId Unique identifier for the trace
	TraceId openapi_types.UUID `json:"trace_id"`
}

// TraceStatus Final status of the trace
type TraceStatus string

// TraceDetail Complete trace details including all associated spans.
// Used for the GET /traces/{trace_id} endpoint.
type TraceDetail struct {
	// Spans All spans belonging to this trace
	Spans []Span `json:"spans"`

	// Trace Represents a distributed trace containing metadata about a single request flow.
	Trace Trace `json:"trace"`
}

// TraceListResponse Paginated response for trace list operations.
// Includes traces and an optional cursor for fetching the next page.
type TraceListResponse struct {
	// NextCursor Cursor for fetching the next page of results.
	// Omit or null when there are no more results.
	NextCursor *string `json:"next_cursor,omitempty"`

	// Traces List of traces matching the query
	Traces []Trace `json:"traces"`
}

// SearchTracesParams defines parameters for SearchTraces.
type SearchTracesParams struct {
	// Query Search query in DSL format
	Query string `form:"query" json:"query"`

	// Limit Maximum number of traces to return
	Limit *int32 `form:"limit,omitempty" json:"limit,omitempty"`
}

// ListEventsBySessionParams defines parameters for ListEventsBySession.
type ListEventsBySessionParams struct {
	// From Start of time range (RFC3339 format)
	From *time.Time `form:"from,omitempty" json:"from,omitempty"`

	// To End of time range (RFC3339 format)
	To *time.Time `form:"to,omitempty" json:"to,omitempty"`

	// Limit Maximum number of events to return (default: 100, max: 1000)
	Limit *int32 `form:"limit,omitempty" json:"limit,omitempty"`
}

// ListTracesParams defines parameters for ListTraces.
type ListTracesParams struct {
	// Service Service name to filter traces
	Service string `form:"service" json:"service"`

	// From Start of time range (RFC3339 format)
	From time.Time `form:"from" json:"from"`

	// To End of time range (RFC3339 format)
	To time.Time `form:"to" json:"to"`

	// Limit Maximum number of traces to return (default: 50, max: 1000)
	Limit *int32 `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Pagination cursor for fetching the next page.
	// Use the `next_cursor` value from the previous response.
	// Encode the Cassandra paging_state as base64.
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Liveness probe
	// (GET /live)
	GetLive(ctx echo.Context) error
	// Readiness probe
	// (GET /ready)
	GetReady(ctx echo.Context) error
	// Search traces (optional)
	// (GET /search)
	SearchTraces(ctx echo.Context, params SearchTracesParams) error
	// List session events
	// (GET /sessions/{session_id}/events)
	ListEventsBySession(ctx echo.Context, sessionId openapi_types.UUID, params ListEventsBySessionParams) error
	// List traces
	// (GET /traces)
	ListTraces(ctx echo.Context, params ListTracesParams) error
	// Get trace by ID
	// (GET /traces/{trace_id})
	GetTraceByID(ctx echo.Context, traceId openapi_types.UUID) error
	// List spans for a trace
	// (GET /traces/{trace_id}/spans)
	ListSpansByTrace(ctx echo.Context, traceId openapi_types.UUID) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetLive converts echo context to params.
func (w *ServerInterfaceWrapper) GetLive(ctx echo.Context) error {
	var err error

	ctx.Set(ApiKeyAuthScopes, []string{})

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetLive(ctx)
	return err
}

// GetReady converts echo context to params.
func (w *ServerInterfaceWrapper) GetReady(ctx echo.Context) error {
	var err error

	ctx.Set(ApiKeyAuthScopes, []string{})

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetReady(ctx)
	return err
}

// SearchTraces converts echo context to params.
func (w *ServerInterfaceWrapper) SearchTraces(ctx echo.Context) error {
	var err error

	ctx.Set(ApiKeyAuthScopes, []string{})

	ctx.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params SearchTracesParams
	// ------------- Required query parameter "query" -------------

	err = runtime.BindQueryParameter("form", true, true, "query", ctx.QueryParams(), &params.Query)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter query: %s", err))
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", ctx.QueryParams(), &params.Limit)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.SearchTraces(ctx, params)
	return err
}

// ListEventsBySession converts echo context to params.
func (w *ServerInterfaceWrapper) ListEventsBySession(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "session_id" -------------
	var sessionId openapi_types.UUID

	err = runtime.BindStyledParameterWithLocation("simple", false, "session_id", runtime.ParamLocationPath, ctx.Param("session_id"), &sessionId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter session_id: %s", err))
	}

	ctx.Set(ApiKeyAuthScopes, []string{})

	ctx.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params ListEventsBySessionParams
	// ------------- Optional query parameter "from" -------------

	err = runtime.BindQueryParameter("form", true, false, "from", ctx.QueryParams(), &params.From)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter from: %s", err))
	}

	// ------------- Optional query parameter "to" -------------

	err = runtime.BindQueryParameter("form", true, false, "to", ctx.QueryParams(), &params.To)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter to: %s", err))
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", ctx.QueryParams(), &params.Limit)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListEventsBySession(ctx, sessionId, params)
	return err
}

// ListTraces converts echo context to params.
func (w *ServerInterfaceWrapper) ListTraces(ctx echo.Context) error {
	var err error

	ctx.Set(ApiKeyAuthScopes, []string{})

	ctx.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params ListTracesParams
	// ------------- Required query parameter "service" -------------

	err = runtime.BindQueryParameter("form", true, true, "service", ctx.QueryParams(), &params.Service)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter service: %s", err))
	}

	// ------------- Required query parameter "from" -------------

	err = runtime.BindQueryParameter("form", true, true, "from", ctx.QueryParams(), &params.From)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter from: %s", err))
	}

	// ------------- Required query parameter "to" -------------

	err = runtime.BindQueryParameter("form", true, true, "to", ctx.QueryParams(), &params.To)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter to: %s", err))
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", ctx.QueryParams(), &params.Limit)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameter("form", true, false, "cursor", ctx.QueryParams(), &params.Cursor)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter cursor: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListTraces(ctx, params)
	return err
}

// GetTraceByID converts echo context to params.
func (w *ServerInterfaceWrapper) GetTraceByID(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "trace_id" -------------
	var traceId openapi_types.UUID

	err = runtime.BindStyledParameterWithLocation("simple", false, "trace_id", runtime.ParamLocationPath, ctx.Param("trace_id"), &traceId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter trace_id: %s", err))
	}

	ctx.Set(ApiKeyAuthScopes, []string{})

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetTraceByID(ctx, traceId)
	return err
}

// ListSpansByTrace converts echo context to params.
func (w *ServerInterfaceWrapper) ListSpansByTrace(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "trace_id" -------------
	var traceId openapi_types.UUID

	err = runtime.BindStyledParameterWithLocation("simple", false, "trace_id", runtime.ParamLocationPath, ctx.Param("trace_id"), &traceId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter trace_id: %s", err))
	}

	ctx.Set(ApiKeyAuthScopes, []string{})

	ctx.Set(BearerAuthScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListSpansByTrace(ctx, traceId)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/live", wrapper.GetLive)
	router.GET(baseURL+"/ready", wrapper.GetReady)
	router.GET(baseURL+"/search", wrapper.SearchTraces)
	router.GET(baseURL+"/sessions/:session_id/events", wrapper.ListEventsBySession)
	router.GET(baseURL+"/traces", wrapper.ListTraces)
	router.GET(baseURL+"/traces/:trace_id", wrapper.GetTraceByID)
	router.GET(baseURL+"/traces/:trace_id/spans", wrapper.ListSpansByTrace)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xbbVPbuLf/KhrvnfnDnTwYSNg2M/uCFtpNS7dMSad3b+mwin2SaJElV5KBLMN3v6Mj",
	"+Sl2ILCw2xf3VYktS0fn4XceexNEMkmlAGF0MLoJdLSAhOKfR0pJZf+IQUeKpYZJEYyCU0NFTFVMwL4n",
	"CnQqhQYykyqhxv5DKOfk4GTsVujemQg6QapkCsowwL0jGUNz618nkxOiDTWZJriiE8A1TVIOwWgQhp3A",
	"nRGMAibM3m7QCcwyBfcT5qCC204Qg6GM4yE0jpndmfKTyuFGZdBZOfigWOlv5XchWzJ1z7ertNwEMwY8",
	"DkbBTMkk6AQKqMaNmLiknMXnntDbgkI5/RMifJCA1nTedvssoaKrgMZ0ysETkq+unB6M3SHkP/b0/xDD",
	"EtCGJqkXwYgkmTZkCuTTm9d7e3svSz5po5iYB7e3luTvGVMQB6Ovged1fta3FqqPLkGYJs2fIFWgrfIQ",
	"Sj6PiQatmRQE7HLUhfyJgpTTJZllInIcZWbZOxO4ryYRTU2mgGQaFLHSVBSXaUJFTGiachZR+wDVA0i0",
	"oGIOraqFR5+zuEnsZ8G+Z0BYDMKwGQOFBJoF047eGpNfDkN4MQjDLuy+nHYHO/GgS3/e2e8OBvv7w+Fg",
	"EIZhGFQ0MstY3GR0x5PjHq8SNFmmQOTMc6vQtQ7SFVEDc6nYX3jvmv4FEWfRRdtpKV1ySVvujnzu6hQi",
	"NmMRiamhZGvG4ZpZXXNWv6LjwCFBoQfTzBgpejqbJsxy6ToYDYZhJ1gGo70wbFNyL/VWMYwP7Z3NAgrd",
	"KEVApsClmGtiZO3C+/tPIw1D53dAw03zgzrp72HZvaQ8A5KAochEp0LQ1KCbIEUzD6IFRBcysy+tevfo",
	"3HH1g/yLcU77w17YChSFXTdZ+GUBojyVyCjKlIKYbHmL90hQV5rdcHe/Gw66O7uTnXC0F47CsLfzv1Wu",
	"xdRA1x57L2IURlYTdZXmUhfb4OQ0peIeNNFMzDkQKx1n+VfMLJgglBhFI+idCbuJJlQBsmKaMR4zMSdT",
	"LqMLbXUsZpb8aWYgdh+1AkacuQPOE90k6dC/LFQ2pYIwQRLGOdMQSRHrmpsa1r3U/qDVSxW3Ohc0aUGG",
	"32gC+ZElB9q9kb1OBFqf0GXidLAFFtQ6UCyt0S1yN9wSGeeo20pK90zXD33xRPioQV2yCDbgg19JzIIa",
	"EimgKFYLHZa8OkccK7r+k9ZzUyoe6iUa5/z8VEwwVJlztLz1to6CwZWPsfRwuKmpPydKrnLwJoinPXTp",
	"3tWcHh0fvZ6Q/yZvPn38QKSKQVn7squW2kBihSu1mSvQ33ngxNi7YMIGY1bazryaWGqtfzP9x6U1dg6f",
	"RMorCJrrX4W2FWOoqUWnBlNtkDpBuu/G1AYgkkgKQ5mwuFkIi05lZkoEtlSDNmTG5dWD8XMiDeUkXkFR",
	"d/YdMLozDDfCUYtO52tNuZRtgWLVKCuhSxslW6jbfh6zfhy2McEM8+gGLfqIVnEntm0CJ04Gj8WTzcHE",
	"5XNNQt4wm275bK+qF/ZokSXWSKQNcjERssGTuBDySljlr/Di4p8BMKq1jJxQbBzSLpmbYGFM2kvALKQF",
	"pLdHk6DjnmWKB6OgT1PWd6DW39ndyyNCq7v4V3cw3H8gfq1zV/BPAdkj4KtQirU4doj5d/O2r6W9ism1",
	"N0/TmYh4hsEf5bwqKwxcemfis4a4YMzbownpu3iwf5OTf0tAxKlkwrRhHO7TJOeAc3eEz1ssBUa6YCFn",
	"PzPggPG/FMyCUfBTv6y49H25pY/xcCl4qhRdFnK/72OH/K1y8R7yDk4fM20++RpO84IndM4EcrJa5/Hc",
	"50ybMjq1bB6jHMBf3ifvguSQS6JMaek0dAYmWiC/FkAEXBti06U23tuX5+7LFoW4b0cLLQp0xo0l8GPC",
	"DJEKMZ9ceShUgEmEkCSRCiqra8YDy3dXv3+J02kSz6K9T4v47Wf2kR2w37+8+/PDZPzXWIS/tGIRsqJJ",
	"+TFyb5azKqEV6r9noJab6o4X/6rytKlDmx6gn4oyxczy1O7oaD1I2XtYHmRm0aL1J2NyAUtCM7OwqOMr",
	"M1tGWncKgk45xNa7p0rGWZSXL5j9dgE0BovmzicG/9M9OBl338OyZB3Fo+2FXgFVoHIipvjrTQ5O775Y",
	"cK1T9u7LhLhlxMgLEA8lEVlqaXCblDRZDA9uLa+YmElXwRSGRlgS81dBOcykmgOZAE2abuVYXnU5NSCi",
	"pbcgBUYxuKQcLQWljoXTHKkqW6acGgvMvTNxJiYWYOzCVMlLZg0uLQyVRjYZRBhCkXccQnXwiFp9TqMr",
	"OxM6S1OpXLluxrgBhWn0Mo9KOlhiJIqKObhtcOd+vtn4UCNVP/1E3gA1mQJ9JrqkxI4SLuzG6D+dPXen",
	"1AKzJ55JYb87ZAoiH4c7om3cVrDKLjmtlRldaRGfZ9PubhgmmuR8Pj0+KErSOcBrT+xBTTnOxOtM2QyA",
	"Ly0UrGgO0yS3ph4ZV/WmQ3J7kIpYBVz5Ui9kxuOK2jlg4SwCD7lefw5SGi2A7PasD3bxglU7Per3r66u",
	"ehRf96Sa9/23un88fn302+lRd9eXkJjhK5p4cDIOOsElKO10cKcXurUyBUFTFoyCvV7Y28N6jVmg7fc5",
	"u0TC5tBa8jWZEq5CY6GR7IYh+fi+dBBGEiZie30oYltQyMFM2Eyj5xU4lweJJWgipCFYKiNULEkMKYgY",
	"RMTyok3haMYYWoE5tlRakHPnIum7YZgbp69XG7g2/ZRTJsr2BlY37wwhbxvGe1rcgiJ7bjvB8BGHYW0b",
	"A1+3Xx7c3nv+uPVDRO8sSahaoku5BGGNP1VyisE4xsFfg1+BcrMIvtnlfQU0Xq4V72srAk3YbFV29isr",
	"W3yUJ4XawgR2I6i17TMRSSEgMuySGVz9mmpNRawolpytua+R5iek6gnEqfxGD5Cou9tWSau/BcTbTs57",
	"D6bCavNDKSm+qZISM12lpiZvyzN2v8A1UBUt1kr8FF/ncUimMYzOjdv5pMPT49LvWBOoxHSFFSPMxpdU",
	"RDbwdptGNKVTxplxZjzJYxuil8LQa+Jdjx5Z9PbuZmTxkHTJG3RFFT9E7Au7MM8lRmdZGO7BDiJ+9YN8",
	"Ae6KqcbItdNqu+ILu8TQ+egClr+4nK+6xtB5i7o6jk1cRIXVVZqAAWVZv4a77tZMWFb6HDsPifJgz7uB",
	"/GcZvLmOZZuW5RyrVQTa2ePZ0Ap2nVWiP9BrlmQJEVkyBVWJUo20jjhTYg3xnLkOUUlsDDOacROMhm39",
	"28QdFIx2wjDsBAkT/mez2HP77V5wqPQJ+39iQ7ZqnPfG0LVUqM1MMwytZhkvnR0GM2Xs7lTithMMnpC4",
	"Iw/1LT7BNYKrJtXumJ7l8PsdUh1aau2LHKm8FeVIhXGd7t+UXaXbvgtW7wpIbGQIjf6z3qQBXbSgKaZ+",
	"VrddZhAtlBSSyzmLKHeVaLJFdQQi9uFx0eza7p2JU49klVi5EkzbMLaMcttcoFU+R8mrpQ9v74MWX/rJ",
	"L1gpAW19/jw+rJTy0FRtfFdaaq1ttwnWPE0Ltok1p4YqlwiXjGupRrahjZ++aKO2UrIMw1H4kJJlk8Qj",
	"ET+OQOxi30Pe7t5o+HI0fPl48ppo7dW/QGuy5WF4RHbCsEMSeo1/hdsPx3G7QaVQH/7bsL5RjcSNrzRr",
	"JJtjPPflGg9G/w7EV+AACRg8PwF5qm2D05nMREy2hMwVDK4tV8r+aIEp2z+UG8JSW901VDyQv2Hug8p6",
	"3d3ehlZqLrxey8NImBTDNnlcVg4wFECCDuiTKziiB0I/A7GPT335nFgSvN/ZSqS2aUKEA1ZMabPt6tuY",
	"r/1RKZb+QSw+uvZXJTfHMmlb1bXpjzaNcMvoHA9w0bPJP27Dl7J5tYnruafh9Rw+ZROyfiAf80Byn8Pn",
	"rGYIFZ8z/JsuZ1j1OH87j+isaXJYcNikQdFuay53LCwuVXDJZKYL0+udiSMRydh9W+b3CCLzczfWSDWZ",
	"Ug37A2eRbWzyjZB2ET+uR/EDZ1Z1YN3c61Zasm7UGMeHi9Hbh4/Q3nae05P/WJ6yQO7WHK3RON3EVUb1",
	"vu10SZjRJFvtXfsiU8VhsaKjWIwslD15Ea/r945rcya6Er0wN/0wo9oQLuVFlhKD89Zb7kLTpQ1fOmeC",
	"GXLFOLdKgFzGDnJu3niOXetOwB3WFDaRea+W48MN0zlP84OSuUoPfhNP8ERzAM8OG34K4CGAUZsLeHq8",
	"yBndwAnqquDEyuoJwWLlvM2j/pYLDaoXQv6WZvEEJLfs+MPA2lswJfKgJW4Gbf1i7uMegGufA6nkAPnM",
	"cnVquVptcvUlG/W7YTayFfFM++oRvtxutM2YJpkGawM4ybCUGREAsdd+j4aECac7WA63NiIz4yAw43wF",
	"UtclAkjzq+XEj5T8P4w9uADRPuDziEjIaeQ/XX54NA49Lahg7cEZ2krpISfwRyw8IL2uJpAPZRW1Bzec",
	"dVudwkGbqs7ffP1mc5bqMMzXb1Zr3cFtNngsI8pJDJfAZZrgVL+bja4OFoz6fW7XLaQ2oxfhizBopkbr",
	"NnI6eXAyJn60wCY8M3Z99wE4/ni503LOSTFO0UapHvXtpz1TzDX0PAr0IpkElheeoY3/U4d9UD9XUMx/",
	"lIjj+6RNgia1kRUbaZazOuXIW7nRJE9QGqWI2vBK67en3qRv1pTeqlMu7RvkFazbb7f/FwAA//8bcAwv",
	"0TkAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
